name: Build and deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.production from repo secrets
        run: |
          cat > .env.production <<'EOF'
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOF

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Ensure export output
        run: |
          # Next 14+ uses `output: 'export'` which writes to .next/output/export
          EXPORT_DIR=".next/output/export"
          if [ -d "$EXPORT_DIR" ] && [ -n "$(ls -A $EXPORT_DIR 2>/dev/null)" ]; then
            echo "Found export in $EXPORT_DIR"
            # copy to ./out for consistency with deploy step
            rm -rf out || true
            cp -R "$EXPORT_DIR" out
          else
            echo "ERROR: export output not found at $EXPORT_DIR. Build may not have produced a static export." >&2
            ls -la .next || true
            exit 1
          fi
      - name: Configure git for deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}


